# baseURL: https://example.org/
# languageCode: en-us
# title: My New Hugo Site

baseURL: "https://milknocandy.github.io/" # url for home page (for github actions deployment)
title: PaperMoon's blog # title for home page
pagination: 
  pagerSize: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  mainSections:
      - posts
      - tech
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "PaperMoon's blog" # title for home page
  description: "This is my home"  # description for home page
  keywords: [Blog, Portfolio, PaperMod]
  author: PaperMoon # default author name for all paper
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "Jan. 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true # show buttons for copy Codes
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true # show Table of Content at the beginning of every paper
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-96x96.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/favicon.svg"
  label:
    text: "PaperMoon's Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tech
        url: tech
      - name: Study
        url: study
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    # - name: x
    #   url: "https://x.com/"
    - name: email
      url: "mailto:milknocandy@outlook.com"
    - name: github
      url: "https://github.com/milknocandy"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/milknocandy/milknocandy.github.io/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: 📝Posts
      url: /posts/
      weight: 10
    - identifier: tech
      name: 🛠️Tech
      url: /tech/
      weight: 20
    - identifier: study
      name: 📚Study
      url: /study/
      weight: 30
    - identifier: archives
      name: 📅Archives
      url: /archives/
      weight: 40
    - identifier: tags
      name: 🏷️Tags
      url: /tags/
      weight: 50
    - identifier: search
      name: 🔍Search
      url: /search/
      weight: 60
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false  # use classes, needed for pygmentsUseClasses above
    anchorLineNos: true
    codeFences: true  # enable code fences
    guessSyntax: true # enable to guess language if not specified
    lineNos: true # enable line numbers
    style: github-dark
  goldmark:
    parser:
      attribute: true
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
        # not translate this
          block:
            - ["$$", "$$"]
          inline:
            - ["$", "$"]
  renderHooks:
    image:
      enableDefault: true

# for Search Page
outputs:
  home:
    - HTML
    - RSS
    - JSON  # is necessary for search page to work

frontmatter:
  # 1. find by "lastmod" key in frontmatter
  # 2. if not found, find by ":fileModTime" (file modification time)
  lastmod: ["lastmod", ":fileModTime"]